name: Update Releases
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  resources:
    name: Update Releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Access Latest Release
        run: gh release view > release-latest.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Releases
        run: python3 src/util/update-releases.py release-latest.txt RELEASES.md
      - name: Commit Changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: RELEASES.md
          commit-msg: Update RELEASES.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
